### ISSUE TITLE
Add LICENSE file (Clarify BSD license)

### ISSUE THREAD

**Issue by koobs** [leforestier/jailconf#1]
Hi! I'm creating a FreeBSD port for this package and would like to clarify which specific BSD license applies to this code

* Add LICENSE file in repository root with verbatim BSD[234]CLAUSE or other BSD license text with your copyright/name header
* Update setup.py Trove Classifier for license to the specific license that applies
* Include LICENSE file in PyPI sdist (via MANIFEST.in:include LICENSE)

Thanks!

**Comment by leforestier** [comment]
Hello!
I'm glad to learn you're making a port out of this library.

I added a LICENSE file to the project with the BSD 2-Clause license, and included it in MANIFEST.in.

About the Trove classifier, there are no classifiers for specific versions of the BSD licenses: https://pypi.org/classifiers/
I read that some have requested that here https://github.com/pypa/trove-classifiers/issues/17 but the issue is still open.

Have a nice day.

**Comment by koobs** [comment]
py-jailconf landed today: https://www.freshports.org/sysutils/py-jailconf/ :)

Thanks for adding the LICENSE file :) I'll update the LICENSE metadata in the port accordingly.

**Comment by koobs** [comment]
Closed by d405475 and 214c2993
